#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 15:00 --qos=short
#SBATCH -J quality_short_reads_DNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user villew7@gmail.com
#SBATCH --output=%x.%j.out

$OUTPUT='/home/haddock/private/Genome_analysis/GenomeAnalysis/analyses/01_preprocessing/01-04-fastqc_dna'

# Load modules
module load bioinfo-tools
module load FastQC

# Execution

# DNA
for i in {65,71,80};
do 
    fastqc -o $OUTPUT -t 2 SRR244130"$i"_1.fastq.gz SRR244130"$i"_2.fastq.gz
done


