#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 6
#SBATCH -t 15:00 --qos=short
#SBATCH -J quality_short_reads_DNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user villew7@gmail.com
#SBATCH --output=%x.%j.out

OUTPUT='/home/haddock/private/Genome_analysis/GenomeAnalysis/analyses/01_preprocessing/10-04-fastqc_dna_longread'
INPUT_PATH='/home/haddock/private/Genome_analysis/GenomeAnalysis/data/raw_data/DNA_reads'

# Load modules
module load bioinfo-tools
module load FastQC

# Execution

# DNA
for i in {66,72,81};
do 
   ( fastqc -o $OUTPUT --threads 2 "${INPUT_PATH}SRR244130${i}.fastq.gz" ) &
done

wait