#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 15
#SBATCH -t 45:00
#SBATCH -J shortread_dna_preprocess
#SBATCH --mail-type=ALL
#SBATCH --mail-user villew7@gmail.com
#SBATCH --output=%x.%j.out

OUTPUT='/home/haddock/private/Genome_analysis/GenomeAnalysis/analyses/01_preprocessing/02-04-trimomatic_rna'
INPUT_PATH='/home/haddock/private/Genome_analysis/GenomeAnalysis/data/raw_data/RNA_reads/'
OUTPUT_FastQC='/home/haddock/private/Genome_analysis/GenomeAnalysis/analyses/01_preprocessing/02-04-trimomatic_rna/02-04-fastqc'

# Load modules
module load bioinfo-tools
module load trimmomatic
module load FastQC

java -jar $TRIMMOMATIC_ROOT/trimmomatic.jar

# Execution

# Loop through all reads with parallelisation 
for i in {56..64};
do 
( 
    # Copy to temp dir
    cp "${INPUT_PATH}SRR245164${i}_1.fastq.gz" $SNIC_TMP
    cp "${INPUT_PATH}SRR245164${i}_2.fastq.gz" $SNIC_TMP

    cd $SNIC_TMP

    # Uncompress the files
    gunzip "SRR245164${i}_1.fastq.gz"
    gunzip "SRR245164${i}_2.fastq.gz"

    # Trim the reads
    trimmomatic PE -threads 2 -phred33 "SRR245164${i}_1.fastq" "SRR245164${i}_2.fastq" "shortread_rna_${i}_1.trimmed.fastq" "shortread_rna_${i}_1un.trimmed.fastq" "shortread_rna_${i}_2.trimmed.fastq" "shortread_rna_${i}_2un.trimmed.fastq" ILLUMINACLIP:/home/haddock/private/Genome_analysis/GenomeAnalysis/scripts/TruSeq3-PE-2.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:20 MINLEN:36
    
    # Quality control of the outputs so we can compare
    fastqc -o $OUTPUT_FastQC --threads 2 "shortread_rna_${i}_1.trimmed.fastq" "shortread_rna_${i}_1un.trimmed.fastq" "shortread_rna_${i}_2.trimmed.fastq" "shortread_rna_${i}_2un.trimmed.fastq"

    # Zip the timmed reads
    gzip -v "shortread_rna_${i}_1.trimmed.fastq" "shortread_rna_${i}_1un.trimmed.fastq" "shortread_rna_${i}_2.trimmed.fastq" "shortread_rna_${i}_2un.trimmed.fastq"
    

    cp *.trimmed.fastq.gz $OUTPUT

) &
done

wait 
